-- LABORER para test de obtener, crear y modificar
-- id 207
INSERT INTO LABORER (LABORERID,ADDRESS,AFP,COMMUNE,CONTRACTID,DATEADMISSION,DATEBIRTH,DEPENDENTS,FIRSTNAME,ISAPRE,LASTNAME,MARITALSTATUS,MOBILENUMBER,NATIONALITY,PHONE,PHOTO,RUT,SECONDLASTNAME,SECONDNAME,TEAMID,TOWN,WEDGE) VALUES 
(207,'Edith Madge 0711',4,'La Pintana',null,null,{ts '1959-02-05 00:00:00.0'},1,'Juan',1,'Salas',2,'83697498',1,'61833825','1.JPG','8858100-8','Roa','Francisco',null,'Santo Tomas',40);
MERGE INTO LABORER (LABORERID,ADDRESS,AFP,COMMUNE,CONTRACTID,DATEADMISSION,DATEBIRTH,DEPENDENTS,FIRSTNAME,ISAPRE,LASTNAME,MARITALSTATUS,MOBILENUMBER,NATIONALITY,PHONE,PHOTO,RUT,SECONDLASTNAME,SECONDNAME,TEAMID,TOWN,WEDGE) 
VALUES (209,'Mariano Gomez 1064',4,'Puente Alto',null,null,{ts '1942-08-02 00:00:00.0'},0,'Juvenal',1,'Pe¤a',2,null,1,null,'3.JPG','4912637-9','Urizar','Alfonso',null,'Las Brisas',40);

-- OBRA PARA TEST
-- id 1
MERGE INTO CONSTRUCTION_SITE (CONSTRUCTION_SITEID,ADDRESS,DELETED,NAME,STATUS,PERSONINCHARGEID) VALUES 
(1,'',0,'Carolina Rabat 4 Etapa B',1,null);

-- ASOCIA EL OBRERO 207 A LA OBRA 1
insert into LABORER_CONSTRUCTIONSITE(LABORERID,CONSTRUCTION_SITEID,ACTIVE,JOB,JOBCODE) VALUES
(207,1,1,1,1);

insert into LABORER_CONSTRUCTIONSITE(LABORERID,CONSTRUCTION_SITEID,ACTIVE,JOB,JOBCODE) VALUES
(209,1,1,1,1);
