CREATE TABLE "LABORER"
(
   LABORERID IDENTITY PRIMARY KEY NOT NULL,
   ADDRESS varchar(255),
   AFP integer NOT NULL,
   COMMUNE varchar(255),
   CONTRACTID integer,
   DATEADMISSION timestamp,
   DATEBIRTH timestamp,
   DEPENDENTS integer,
   FIRSTNAME varchar(255) NOT NULL,
   ISAPRE integer NOT NULL,
   LASTNAME varchar(255) NOT NULL,
   MARITALSTATUS integer NOT NULL,
   MOBILENUMBER varchar(255),
   NATIONALITY integer NOT NULL,
   PHONE varchar(255),
   PHOTO varchar(255),
   RUT varchar(255) NOT NULL,
   SECONDLASTNAME varchar(255),
   SECONDNAME varchar(255),
   TEAMID bigint,
   TOWN varchar(255),
   WEDGE integer
)
;
CREATE UNIQUE INDEX PK_LABORER ON "LABORER"(LABORERID)
;

-- ROLE 

CREATE TABLE "ROLE"
(
   ROLEID IDENTITY PRIMARY KEY NOT NULL,
   DESCRIPTION varchar(255),
   NAME varchar(255) NOT NULL
)
;
CREATE UNIQUE INDEX PK_ROLE ON "ROLE"(ROLEID)
;


-- permission

CREATE TABLE "PERMISSIONS"
(
   ROLEID bigint NOT NULL,
   ROLE_PERMISSIONS varchar(255)
)
;
ALTER TABLE "PERMISSIONS"
ADD CONSTRAINT FK_PERMISSIONS
FOREIGN KEY (ROLEID)
REFERENCES "ROLE"(ROLEID)
;
CREATE INDEX FK_INDX_PERMISSIONS ON "PERMISSIONS"(ROLEID)
;


-- USER

CREATE TABLE "USER"
(
   USERID IDENTITY PRIMARY KEY NOT NULL,
   DELETED boolean,
   EMAIL varchar(255) NOT NULL,
   FIRSTNAME varchar(255) NOT NULL,
   LASTNAME varchar(255) NOT NULL,
   PASSWORD varchar(255),
   RUT varchar(255) NOT NULL,
   SALT varchar(255),
   STATUS integer NOT NULL,
   ROLEID bigint
)
;
ALTER TABLE "USER"
ADD CONSTRAINT FK_USER_ROLE
FOREIGN KEY (ROLEID)
REFERENCES "ROLE"(ROLEID)
;
CREATE INDEX FK_INDX_ROLE ON "USER"(ROLEID)
;
CREATE UNIQUE INDEX UK_EMAIL ON "USER"(EMAIL)
;
CREATE UNIQUE INDEX PK_USER ON "USER"(USERID)
;

-- CONSTRUCTION SITE


CREATE TABLE "CONSTRUCTION_SITE"
(
   CONSTRUCTION_SITEID IDENTITY PRIMARY KEY NOT NULL,
   ADDRESS varchar(255),
   DELETED boolean,
   NAME varchar(255) NOT NULL,
   STATUS integer NOT NULL,
   PERSONINCHARGEID bigint
)
;
ALTER TABLE "CONSTRUCTION_SITE"
ADD CONSTRAINT FK_CS_USER
FOREIGN KEY (PERSONINCHARGEID)
REFERENCES "USER"(USERID)
;
CREATE INDEX FK_INDX_CS ON "CONSTRUCTION_SITE"(PERSONINCHARGEID)
;
CREATE UNIQUE INDEX PK_CS ON "CONSTRUCTION_SITE"(CONSTRUCTION_SITEID)
;

-- LABORER_CONSTRUCTIONSITE

CREATE TABLE "LABORER_CONSTRUCTIONSITE"
(
   LABORER_CONSTRUCTIONSITEID IDENTITY PRIMARY KEY NOT NULL,
   LABORERID integer NOT NULL,
   ACTIVE smallint,
   JOB integer not null,
   JOBCODE integer not null,
   CONSTRUCTION_SITEID integer NOT NULL
)
;
ALTER TABLE "LABORER_CONSTRUCTIONSITE"
ADD CONSTRAINT FK_LC_LABORER
FOREIGN KEY (LABORERID)
REFERENCES "LABORER"(LABORERID)
;
CREATE INDEX FK_IDX_LC_LABORER ON "LABORER_CONSTRUCTIONSITE"(LABORERID)
;
ALTER TABLE "LABORER_CONSTRUCTIONSITE"
ADD CONSTRAINT FK_LC_CS
FOREIGN KEY (CONSTRUCTION_SITEID)
REFERENCES "CONSTRUCTION_SITE"(CONSTRUCTION_SITEID)
;
CREATE INDEX FK_IDX_LC_CS ON "LABORER_CONSTRUCTIONSITE"(CONSTRUCTION_SITEID)
;
CREATE UNIQUE INDEX PK_LC ON "LABORER_CONSTRUCTIONSITE"(LABORER_CONSTRUCTIONSITEID)
;

-- ABSENCE

CREATE TABLE "ABSENCE"
(
   ABSENCEID IDENTITY PRIMARY KEY NOT NULL,
   ABSENCE_TYPE integer,
   DESCRIPTION varchar(255),
   FROM_DATE date,
   TO_DATE date,
   LABORER_CONSTRUCTIONSITEID bigint
)
;
ALTER TABLE "ABSENCE"
ADD CONSTRAINT FK_BS24KVJFK3V03QEG76BCE1MAO
FOREIGN KEY (LABORER_CONSTRUCTIONSITEID)
REFERENCES "LABORER_CONSTRUCTIONSITE"(LABORER_CONSTRUCTIONSITEID)
;
CREATE UNIQUE INDEX PK_ABSENCE ON "ABSENCE"(ABSENCEID)
;
CREATE INDEX FK_INDX_ABSENCE_LC ON "ABSENCE"(LABORER_CONSTRUCTIONSITEID)
;

-- TOOL

CREATE TABLE "TOOL"
(
   TOOLID bigint PRIMARY KEY NOT NULL,
   DATEBUY timestamp NOT NULL,
   FEE integer,
   NAME varchar(255) NOT NULL,
   PRICE integer,
   STATUS integer NOT NULL,
   LABORER_CONSTRUCTIONSITEID bigint not null
)
;
ALTER TABLE "TOOL"
ADD CONSTRAINT FK_TOOL_LC
FOREIGN KEY (LABORER_CONSTRUCTIONSITEID)
REFERENCES "LABORER_CONSTRUCTIONSITE"(LABORER_CONSTRUCTIONSITEID)
;
CREATE UNIQUE INDEX PK_TOOL ON "TOOL"(TOOLID)
;
CREATE INDEX FK_INDX_TOOL_LC ON "TOOL"(LABORER_CONSTRUCTIONSITEID)
;

-- VACATION

CREATE TABLE "VACATION"
(
   VACATIONID IDENTITY PRIMARY KEY NOT NULL,
   FROM_DATE date,
   TO_DATE date,
   LABORER_CONSTRUCTIONSITEID bigint not null
)
;
ALTER TABLE "VACATION"
ADD CONSTRAINT FK_VACATION_LC
FOREIGN KEY (LABORER_CONSTRUCTIONSITEID)
REFERENCES "LABORER_CONSTRUCTIONSITE"(LABORER_CONSTRUCTIONSITEID)
;
CREATE INDEX FK_INDX_VACATION_LC ON "VACATION"(LABORER_CONSTRUCTIONSITEID)
;
CREATE UNIQUE INDEX PK_VACATION ON "VACATION"(VACATIONID)
;


-- ACCIDENTS

CREATE TABLE "ACCIDENT"
(
   ACCIDENTID IDENTITY PRIMARY KEY NOT NULL,
   ACCIDENT_LEVEL integer,
   DESCRIPTION varchar(255),
   FROM_DATE date,
   TO_DATE date,
   WASNEGLIGENCE boolean NOT NULL,
   LABORER_CONSTRUCTIONSITEID bigint
)
;
ALTER TABLE "ACCIDENT"
ADD CONSTRAINT FK_ACCIDENT_LABORER
FOREIGN KEY (LABORER_CONSTRUCTIONSITEID)
REFERENCES "LABORER_CONSTRUCTIONSITE"(LABORER_CONSTRUCTIONSITEID)
;
CREATE INDEX FK_INDX_ACCIDENT_LABORER ON "ACCIDENT"(LABORER_CONSTRUCTIONSITEID)
;
CREATE UNIQUE INDEX PK_ACCIDENT ON "ACCIDENT"(ACCIDENTID)
;

-- WAGE_CONFIGURATIONS

CREATE TABLE "WAGE_CONFIGURATIONS"
(
   WAGE_CONFIGURATIONSID bigint PRIMARY KEY NOT NULL,
   COLLATION double,
   MINIMUM_WAGE double,
   MOBILIZATION double
)
;
CREATE UNIQUE INDEX PK_WG ON "WAGE_CONFIGURATIONS"(WAGE_CONFIGURATIONSID)
;


-- MOBILIZATION2
CREATE TABLE "MOBILIZATION2"
(
   WAGE_CONFIGURATIONSID IDENTITY NOT NULL,
   AMOUNT double,
   LINKED_CONSTRUCTION_SITEID bigint
)
;
ALTER TABLE "MOBILIZATION2"
ADD CONSTRAINT FK_MOBILIZATION2_CS
FOREIGN KEY (LINKED_CONSTRUCTION_SITEID)
REFERENCES "CONSTRUCTION_SITE"(CONSTRUCTION_SITEID)
;
ALTER TABLE "MOBILIZATION2"
ADD CONSTRAINT FK_MOBILIZATION2_WC
FOREIGN KEY (WAGE_CONFIGURATIONSID)
REFERENCES "WAGE_CONFIGURATIONS"(WAGE_CONFIGURATIONSID)
;
CREATE INDEX FK_INDX_MOB2_CS ON "MOBILIZATION2"(LINKED_CONSTRUCTION_SITEID)
;
CREATE INDEX FK_INDX_MOB2_WC ON "MOBILIZATION2"(WAGE_CONFIGURATIONSID)
;

-- TEAM

CREATE TABLE "TEAM"
(
   TEAMID IDENTITY PRIMARY KEY NOT NULL,
   DATE timestamp,
   DELETED boolean,
   NAME varchar(255) NOT NULL,
   STATUS integer NOT NULL,
   CONSTRUCTION_SITEID bigint,
   LABORERID bigint
)
;
ALTER TABLE "TEAM"
ADD CONSTRAINT FK_TEAM_LABORER
FOREIGN KEY (LABORERID)
REFERENCES "LABORER"(LABORERID)
;
ALTER TABLE "TEAM"
ADD CONSTRAINT FK_TEAM_CS
FOREIGN KEY (CONSTRUCTION_SITEID)
REFERENCES "CONSTRUCTION_SITE"(CONSTRUCTION_SITEID)
;
CREATE INDEX FK_INDX_TEAM_LABORER ON "TEAM"(LABORERID)
;
CREATE UNIQUE INDEX PK_TEAM ON "TEAM"(TEAMID)
;
CREATE INDEX FK_INDX_TEAM_CS ON "TEAM"(CONSTRUCTION_SITEID)
;



-- CONSTRUCTION SITE TEAM

CREATE TABLE "CONSTRUCTION_SITE_TEAM"
(
   CST_CSID bigint NOT NULL,
   TEAMS_TEAMID bigint NOT NULL
)
;
ALTER TABLE "CONSTRUCTION_SITE_TEAM"
ADD CONSTRAINT FK_CST_CS
FOREIGN KEY (CST_CSID)
REFERENCES "CONSTRUCTION_SITE"(CONSTRUCTION_SITEID)
;
ALTER TABLE "CONSTRUCTION_SITE_TEAM"
ADD CONSTRAINT FK_CST_TEAM
FOREIGN KEY (TEAMS_TEAMID)
REFERENCES "TEAM"(TEAMID)
;
CREATE INDEX FK_INDX_CS_TEAM ON "CONSTRUCTION_SITE_TEAM"(CST_CSID)
;
CREATE UNIQUE INDEX UK_INDX_CS ON "CONSTRUCTION_SITE_TEAM"(TEAMS_TEAMID)
;
